data:
  augmentations:
    random_horizontal_flip: 0.5
  color_full_scale: 0
  dataset: cityscapes
  dataset_seed: same
  generated_depth_dir: /user/work/ig23200/sde_seg/generated_depth/
  only_sequences_with_segmentation: true
  path: /user/work/ig23200/sde_seg/raw/
  restrict_to_subset:
    mode: fixed
    n_subset: 372
    subset:
    - 2403
    - 1150
    - 336
    - 2071
    - 382
    - 2563
    - 184
    - 1044
    - 2460
    - 1553
    - 1451
    - 641
    - 1233
    - 416
    - 152
    - 2868
    - 1211
    - 1704
    - 2323
    - 1255
    - 2538
    - 356
    - 2703
    - 914
    - 1110
    - 2531
    - 1981
    - 2894
    - 2430
    - 1234
    - 2729
    - 768
    - 2054
    - 2478
    - 1937
    - 2865
    - 1103
    - 1620
    - 1384
    - 1711
    - 1308
    - 1658
    - 2462
    - 1741
    - 2888
    - 2126
    - 2726
    - 2062
    - 158
    - 2425
    - 2638
    - 2507
    - 2664
    - 2604
    - 114
    - 2684
    - 259
    - 2897
    - 2445
    - 2470
    - 525
    - 1629
    - 2451
    - 2442
    - 109
    - 1376
    - 1133
    - 1895
    - 352
    - 735
    - 2912
    - 2265
    - 234
    - 1266
    - 636
    - 1170
    - 650
    - 2280
    - 1471
    - 359
    - 1682
    - 831
    - 2471
    - 1213
    - 1223
    - 959
    - 281
    - 2590
    - 2318
    - 274
    - 2621
    - 1390
    - 2322
    - 2529
    - 2298
    - 2651
    - 460
    - 411
    - 2021
    - 2457
    - 754
    - 2450
    - 1615
    - 2970
    - 2717
    - 2366
    - 851
    - 2536
    - 2301
    - 1614
    - 2176
    - 2892
    - 1507
    - 1960
    - 1112
    - 809
    - 715
    - 422
    - 485
    - 1459
    - 2637
    - 2611
    - 1294
    - 2065
    - 1361
    - 1570
    - 2329
    - 823
    - 1674
    - 796
    - 1669
    - 1097
    - 2039
    - 524
    - 758
    - 632
    - 2852
    - 1697
    - 277
    - 1031
    - 1176
    - 2753
    - 185
    - 1239
    - 2525
    - 630
    - 2654
    - 836
    - 2855
    - 337
    - 2055
    - 1870
    - 642
    - 2118
    - 279
    - 720
    - 538
    - 2587
    - 2052
    - 2649
    - 2860
    - 811
    - 956
    - 280
    - 794
    - 1338
    - 2047
    - 2895
    - 1578
    - 2891
    - 849
    - 616
    - 1275
    - 958
    - 2511
    - 2535
    - 2650
    - 2331
    - 2830
    - 2440
    - 646
    - 2572
    - 1842
    - 1319
    - 2310
    - 2785
    - 495
    - 1976
    - 1194
    - 2446
    - 2302
    - 1257
    - 694
    - 17
    - 649
    - 2122
    - 1693
    - 803
    - 2386
    - 1061
    - 2311
    - 1331
    - 736
    - 2037
    - 2059
    - 387
    - 1700
    - 2456
    - 2959
    - 624
    - 310
    - 2333
    - 230
    - 2924
    - 233
    - 1915
    - 2148
    - 2898
    - 1164
    - 2593
    - 2363
    - 1177
    - 1809
    - 2063
    - 2123
    - 1710
    - 1120
    - 2095
    - 2073
    - 2805
    - 2048
    - 165
    - 1030
    - 813
    - 631
    - 655
    - 880
    - 638
    - 610
    - 2705
    - 907
    - 45
    - 2312
    - 134
    - 1698
    - 2325
    - 2798
    - 672
    - 2486
    - 1147
    - 2861
    - 2527
    - 2685
    - 2098
    - 755
    - 1586
    - 1494
    - 1220
    - 1263
    - 1472
    - 1310
    - 2441
    - 806
    - 1993
    - 1709
    - 2923
    - 1563
    - 1606
    - 2626
    - 1203
    - 668
    - 2238
    - 2093
    - 2288
    - 1573
    - 1980
    - 2306
    - 1433
    - 1184
    - 1212
    - 353
    - 2020
    - 2886
    - 2005
    - 604
    - 1082
    - 2064
    - 1690
    - 2028
    - 2795
    - 348
    - 810
    - 1328
    - 904
    - 2215
    - 2652
    - 2560
    - 2672
    - 383
    - 927
    - 529
    - 399
    - 220
    - 2314
    - 600
    - 1254
    - 1142
    - 1613
    - 2796
    - 1152
    - 2443
    - 2056
    - 1436
    - 1407
    - 588
    - 578
    - 700
    - 1670
    - 1495
    - 2645
    - 881
    - 2546
    - 191
    - 1276
    - 219
    - 1218
    - 1982
    - 699
    - 2859
    - 91
    - 159
    - 2640
    - 1296
    - 2285
    - 2539
    - 335
    - 680
    - 484
    - 698
    - 1942
    - 2173
    - 2405
    - 1725
    - 1520
    - 1598
    - 1135
    - 2696
    - 1188
    - 1452
    - 439
    - 214
    - 2407
    - 1449
    - 173
    - 345
    - 690
    - 2300
    - 1125
    - 360
    - 713
    - 2474
    - 1278
    - 922
    - 2232
    - 452
    - 2197
    - 2731
    - 926
    - 535
    - 2544
    - 1027
    - 2743
  shuffle_trainset: true
  val_downsample_gt: true
  val_split: val
general:
  tag: cityscapes_sel_ds_us_pad_transfer_dcompgt0030_ctcosinew0lam1p00_D372fixed_S7_sgdLr1E-021E-031E-061E-03stepx_clip10False_m1s1_crop512x512bs2_flip_dec6_lr5_fd2_crop512x512bs4_l9i7Trueos1_Unlab1.0depthcompFPLFalsejitblur
machine: bp1
model:
  arch: joint_segmentation_depth
  backbone_name: resnet101
  backbone_pretraining: mono_cityscapes_1024x512_r101dil_aspp_dec6_lr5_fd2_crop512x512bs4
  depth_args:
    aspp_rates:
    - 6
    - 12
    - 18
    intermediate_aspp: true
    max_scale_size: !!python/tuple
    - 512
    - 512
    num_ch_dec:
    - 64
    - 128
    - 128
    - 256
    - 256
  depth_estimator_weights: mono_cityscapes_1024x512_r101dil_aspp_dec6_lr5_fd2_crop512x512bs4
  depth_pretraining: mono_cityscapes_1024x512_r101dil_aspp_dec6_lr5_fd2_crop512x512bs4
  disable_monodepth: false
  disable_pose: false
  enable_imnet_encoder: false
  freeze_backbone: false
  freeze_depth: false
  freeze_pose: false
  freeze_segmentation: false
  pose_model_input: pairs
  pose_pretraining: mono_cityscapes_1024x512_r101dil_aspp_dec6_lr5_fd2_crop512x512bs4
  provide_uncropped_for_pose: false
  replace_stride_with_dilation:
  - false
  - false
  - true
  segmentation_args:
    distillation_layer: 7
    final_layer: 9
    output_stride: 1
    projection_mode: single
    side_output: true
    weights: mono_cityscapes_1024x512_r101dil_aspp_dec6_lr5_fd2_crop512x512bs4
  segmentation_name: mtl_pad
  variant: sel_ds_us_pad_transfer_dcompgt0030_ctcosinew0lam1p00
monodepth_options:
  crop_h: 512
  crop_w: 512
  frame_ids:
  - 0
  - -1
  - 1
  height: 512
  num_scales: 4
  width: 1024
name: 2026-05-04_22-47-0915_tag=cityscapes_sel_ds_us_pad_transfer_dcompgt0030_ctcosinew0lam1p00_D372fixed_S7_sgdLr1E-021E-031E-061E-03stepx_clip10False_m1s1_crop512x512bs2_flip_dec6_lr5_fd2_crop512x512bs4_l9i7Trueos1_Unlab1_0depthcompFPLFalsejitblur
seed: 7
training:
  amp: false
  batch_size: 2
  clip_grad_norm: 10
  cross_task_lambda: 1.0
  cross_task_type: cosine
  cross_task_warmup_iters: 0
  disable_depth_estimator: true
  disable_depth_grad_clip: false
  early_stopping: null
  feat_dist_lambda: 0.0
  log_path: /user/work/ig23200/sde_seg/logs//cityscapes_joint_222/2026-05-04_22-47-0915_tag=cityscapes_sel_ds_us_pad_transfer_dcompgt0030_ctcosinew0lam1p00_D372fixed_S7_sgdLr1E-021E-031E-061E-03stepx_clip10False_m1s1_crop512x512bs2_flip_dec6_lr5_fd2_crop512x512bs4_l9i7Trueos1_Unlab1_0depthcompFPLFalsejitblur
  lr_schedule:
    gamma: 0.1
    name: step_lr
    step_size: 30000
  monodepth_lambda: 1
  monodepth_loss:
    avg_reprojection: false
    disable_automasking: false
    disparity_smoothness: 0.001
    max_depth: 100
    min_depth: 0.1
    no_ssim: false
    test_max_depth: 80
    test_min_depth: 0.001
  n_tensorboard_imgs: 20
  n_tensorboard_trainimgs: 0
  n_workers: 2
  optimizer:
    backbone_lr: 0.001
    lr: 0.01
    momentum: 0.9
    name: sgd
    pose_lr: 1.0e-06
    weight_decay: 0.0005
  print_interval: 100
  pseudo_depth_lambda: 0.0
  resume: null
  save_model: true
  save_monodepth_ema: false
  save_separate_monodepth_models: false
  segmentation_lambda: 1
  segmentation_loss:
    name: cross_entropy
  train_iters: 40000
  unlabeled_segmentation:
    backward_first_pseudo_label: false
    blur: true
    color_jitter: true
    consistency_weight: 1.0
    debug_image: true
    depthcomp_foreground_threshold: 0
    depthcomp_margin: 0.03
    depthmix_online_depth: true
    mix_mask: depthcomp
    mix_use_gt: true
    only_unlabeled: false
  val_batch_size: 2
  val_interval:
    '0': 100
    '100': 2500
    '30000': 500
